// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LNoUiGj6u_cBVv5kWIeNnjvrYGPNE0M',
    appId: '1:542234644935:web:947d76870a8e08c93e09e2',
    messagingSenderId: '542234644935',
    projectId: 'shakeagram',
    authDomain: 'shakeagram.firebaseapp.com',
    storageBucket: 'shakeagram.appspot.com',
    measurementId: 'G-FNPJSK9BV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACIoHfSHzTLoscA8lTO2sAV5BEqC6mzrs',
    appId: '1:542234644935:android:4f89e376f8646d103e09e2',
    messagingSenderId: '542234644935',
    projectId: 'shakeagram',
    storageBucket: 'shakeagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4YL7tFw2AQtZQPFUBVN8nYE8NdjCtYBY',
    appId: '1:542234644935:ios:d2e71203e5366ef23e09e2',
    messagingSenderId: '542234644935',
    projectId: 'shakeagram',
    storageBucket: 'shakeagram.appspot.com',
    iosClientId: '542234644935-00bm923aubapauldu1685f2kvklghu0c.apps.googleusercontent.com',
    iosBundleId: 'com.shakeagram.mohrs',
  );
}
